schema_version = "1.0.0"

id = "render_email_notifier"
version = "1.0.2"
name = "Render Email Notifier"
tagline = "Send an email notification after render completes"

type = "add-on"
maintainer = "Nguyen Phuc Nguyen"

homepage = "https://github.com/NguyenNP-24/Render-Email-Notifier-Blender"
source = "https://github.com/NguyenNP-24/Render-Email-Notifier-Blender"
tracker = "https://github.com/NguyenNP-24/Render-Email-Notifier-Blender/issues"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Pipeline", "Render"]

[permissions]
network = "true"


